name: Check YouTube Live

on:
  schedule:
    - cron: "*/10 * * * *"  # 每 10 分钟检查一次
  workflow_dispatch:        # 手动触发

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests redis

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          CHANNEL_IDS: ${{ secrets.CHANNEL_IDS }}
          UPSTASH_REDIS_URL: ${{ secrets.UPSTASH_REDIS_URL }}
          HOLODEX_API_KEY: $({ secrets.HOLODEX_API_KEY})
        run: python check_Live_Status.py
